In [41]:
import pandas as pf
import numpy as np
import yfinance as yf

In [42]:
MACRO = {
    "^NDX": "Nasdaq-100",       # Nasdaq-100 index
    "^VIX": "Volatility",       # implied volatility (fear index)
    "^TNX": "10y_treasury_yield",       # 10-year Treasury yield
    "^IRX": "3month_treasury_yield",       # 3-month Treasury yield
    "CL=F": "crude_oil",       # WTI crude oil futures
    "DX-Y.NYB": "US_dollar",   # US dollar index
    "GC=F": "gold", 
    "SI=F": "silver"    # gold futures
}

tickers = list(MACRO.keys())
print(tickers)

['^NDX', '^VIX', '^TNX', '^IRX', 'CL=F', 'DX-Y.NYB', 'GC=F', 'SI=F']

In [65]:

# We download the market 
df = yf.download(tickers, start='2010-01-01', end='2026-10-12')[['Open', 'Close','High','Low']]

df

[*********************100%***********************]  8 of 8 completed

Price            Open                                             \
Ticker           CL=F    DX-Y.NYB         GC=F       SI=F   ^IRX
Date
2010-01-04  79.629997   77.930000  1117.699951  17.440001  0.080
2010-01-05  81.629997   77.370003  1118.099976  17.781000  0.060
2010-01-06  81.430000   77.650002  1135.900024  18.163000  0.060
2010-01-07  83.199997   77.370003  1133.099976  18.333000  0.045
2010-01-08  82.650002   77.980003  1138.199951  18.458000  0.045
...               ...         ...          ...        ...    ...
2026-10-05  91.769997  101.919998  4169.399902  61.520000  3.993
2026-10-06  89.269997  102.139999  4169.200195  60.919998  4.035
2026-10-07  89.959999  101.889999  4195.000000  60.880001  4.037
2026-10-08  89.000000  102.230003  4139.899902  59.063999  4.043
2026-10-09  91.290001  102.129997  4159.700195  60.669998  4.045

Price                                           Close              ...   High  \
Ticker              ^NDX   ^TNX       ^VIX       CL=F    DX-Y.NYB  ...   ^TNX
Date                                                               ...
2010-01-04   1882.689941  3.859  21.680000  81.510002   77.529999  ...  3.859
2010-01-05   1887.280029  3.790  20.049999  81.769997   77.620003  ...  3.800
2010-01-06   1887.910034  3.771  19.590000  83.180000   77.489998  ...  3.837
2010-01-07   1878.160034  3.845  19.680000  82.660004   77.910004  ...  3.859
2010-01-08   1870.900024  3.843  19.270000  82.750000   77.470001  ...  3.851
...                  ...    ...        ...        ...         ...  ...    ...
2026-10-05  30812.759766  5.273  16.240000  89.430000  102.169998  ...  5.349
2026-10-06  31255.400391  5.273  15.500000  89.440002  101.830002  ...  5.303
2026-10-07  30976.250000  5.341  15.210000  88.279999  102.239998  ...  5.364
2026-10-08  30985.230469  5.324  15.680000  91.489998  102.139999  ...  5.331
2026-10-09  30900.060547  5.236  15.340000  91.849998  102.209999  ...  5.280

Price                        Low                                             \
Ticker           ^VIX       CL=F    DX-Y.NYB         GC=F       SI=F   ^IRX
Date
2010-01-04  21.680000  79.629997   77.260002  1097.099976  16.870001  0.055
2010-01-05  20.129999  80.949997   77.089996  1115.000000  17.575001  0.040
2010-01-06  19.680000  80.849998   77.360001  1120.699951  17.840000  0.045
2010-01-07  19.709999  82.260002   77.300003  1129.199951  18.090000  0.040
2010-01-08  19.270000  81.800003   77.349998  1122.699951  18.120001  0.035
...               ...        ...         ...          ...        ...    ...
2026-10-05  16.379999  88.739998  101.860001  4150.399902  60.868999  3.990
2026-10-06  15.540000  86.860001  101.750000  4130.700195  60.919998  4.035
2026-10-07  16.010000  87.959999  101.889999  4091.199951  59.529999  4.035
2026-10-08  16.459999  88.769997  102.029999  4128.100098  58.915001  4.040
2026-10-09  15.340000  90.010002  101.919998  4156.100098  60.669998  4.045

Price
Ticker              ^NDX   ^TNX       ^VIX
Date
2010-01-04   1881.630005  3.808  20.030001
2010-01-05   1877.520020  3.749  19.340000
2010-01-06   1873.900024  3.761  18.770000
2010-01-07   1867.619995  3.800  18.700001
2010-01-08   1868.550049  3.775  18.110001
...                  ...    ...        ...
2026-10-05  30798.419922  5.264  15.480000
2026-10-06  31208.199219  5.256  14.960000
2026-10-07  30904.460938  5.269  14.970000
2026-10-08  30556.400391  5.223  15.150000
2026-10-09  30770.050781  5.234  14.770000

[4225 rows x 32 columns]

In [66]:
# columns are (field, ticker): rename the ticker level with MACRO
df = df.rename(columns=MACRO, level=1)
df.head()

Price            Open                                     \
Ticker      crude_oil  US_dollar         gold     silver
Date
2010-01-04  79.629997  77.930000  1117.699951  17.440001
2010-01-05  81.629997  77.370003  1118.099976  17.781000
2010-01-06  81.430000  77.650002  1135.900024  18.163000
2010-01-07  83.199997  77.370003  1133.099976  18.333000
2010-01-08  82.650002  77.980003  1138.199951  18.458000

Price                                                                        \
Ticker     3month_treasury_yield   Nasdaq-100 10y_treasury_yield Volatility
Date
2010-01-04                 0.080  1882.689941              3.859  21.680000
2010-01-05                 0.060  1887.280029              3.790  20.049999
2010-01-06                 0.060  1887.910034              3.771  19.590000
2010-01-07                 0.045  1878.160034              3.845  19.680000
2010-01-08                 0.045  1870.900024              3.843  19.270000

Price           Close             ...               High             \
Ticker      crude_oil  US_dollar  ... 10y_treasury_yield Volatility
Date                              ...
2010-01-04  81.510002  77.529999  ...              3.859  21.680000
2010-01-05  81.769997  77.620003  ...              3.800  20.129999
2010-01-06  83.180000  77.489998  ...              3.837  19.680000
2010-01-07  82.660004  77.910004  ...              3.859  19.709999
2010-01-08  82.750000  77.470001  ...              3.851  19.270000

Price             Low                                     \
Ticker      crude_oil  US_dollar         gold     silver
Date
2010-01-04  79.629997  77.260002  1097.099976  16.870001
2010-01-05  80.949997  77.089996  1115.000000  17.575001
2010-01-06  80.849998  77.360001  1120.699951  17.840000
2010-01-07  82.260002  77.300003  1129.199951  18.090000
2010-01-08  81.800003  77.349998  1122.699951  18.120001

Price
Ticker     3month_treasury_yield   Nasdaq-100 10y_treasury_yield Volatility
Date
2010-01-04                 0.055  1881.630005              3.808  20.030001
2010-01-05                 0.040  1877.520020              3.749  19.340000
2010-01-06                 0.045  1873.900024              3.761  18.770000
2010-01-07                 0.040  1867.619995              3.800  18.700001
2010-01-08                 0.035  1868.550049              3.775  18.110001

[5 rows x 32 columns]

In [67]:
open  = df["Open"]["Nasdaq-100"]
close = df["Close"]["Nasdaq-100"]

In [68]:
df["up/down"] = (close >= open).astype(int)

In [69]:
df.to_feather("data/treated.feather")