In [41]:
import pandas as pf
import numpy as np
import yfinance as yf

In [98]:
MACRO = {
    "^NDX": "Nasdaq-100",       # Nasdaq-100 index
    "^VIX": "Volatility",       # implied volatility (fear index)
    "^TNX": "10y_treasury_yield",       # 10-year Treasury yield
    "^IRX": "3month_treasury_yield",       # 3-month Treasury yield
    "CL=F": "crude_oil",       # WTI crude oil futures
    "DX-Y.NYB": "US_dollar",   # US dollar index
    "GC=F": "gold", 
    "SI=F": "silver",  # gold futures
}

tickers = list(MACRO.keys())
print(tickers)

['^NDX', '^VIX', '^TNX', '^IRX', 'CL=F', 'DX-Y.NYB', 'GC=F', 'SI=F']

In [104]:
NASDAQ_FEATURES = {
    # --- INDICES ET VOLATILITÉ ---
    "^NDX": "Nasdaq_100",                     # Target index
    "^IXIC": "Nasdaq_composite",              # Broad tech market index
    "^VXN": "Nasdaq_volatility",              # Nasdaq-100 implied volatility (Tech fear index)
    "^VIX": "Volatility",                     # S&P 500 implied volatility (Market fear index)

    # --- interest ---
    "^IRX": "3month_treasury_yield",          # 3-month Treasury yield
    "^FVX": "5y_treasury_yield",              # 5-year Treasury yield
    "^TNX": "10y_treasury_yield",             # 10-year Treasury yield (Tech discounting rate)
    "^TYX": "30y_treasury_yield",             # 30-year Treasury yield

    # --- MATIÈRES PREMIÈRES ET DEVISES ---
    "DX-Y.NYB": "US_dollar",                  # US dollar index (DXY)
    "CL=F": "crude_oil",                      # WTI crude oil futures
    "GC=F": "gold",                           # Gold futures
    "SI=F": "silver",                         # Silver futures
    "BTC-USD": "Bitcoin",                     # Bitcoin USD (Risk-on sentiment proxy)
}

tickers1 = list(NASDAQ_FEATURES.keys())
print(tickers1)

['^NDX', '^IXIC', '^VXN', '^VIX', '^IRX', '^FVX', '^TNX', '^TYX', 'DX-Y.NYB', 'CL=F', 'GC=F', 'SI=F', 'BTC-USD']

In [110]:

# We download the market 
df = yf.download(tickers1, start='2018-01-01', end='2026-10-12')[['Open', 'Close']]

df

[*********************100%***********************]  13 of 13 completed

Price               Open                                                 \
Ticker           BTC-USD       CL=F    DX-Y.NYB         GC=F       SI=F
Date
2018-01-01  14112.200195        NaN         NaN          NaN        NaN
2018-01-02  13625.000000  60.200001   92.239998  1302.300049  17.155001
2018-01-03  14978.200195  60.389999   91.820000  1320.000000  17.080000
2018-01-04  15270.700195  61.959999   92.220001  1319.400024  17.084999
2018-01-05  15477.200195  61.900002   91.870003  1320.300049  17.205000
...                  ...        ...         ...          ...        ...
2026-10-07  85554.796875  89.959999  101.889999  4195.000000  60.880001
2026-10-08  83281.468750  89.000000  102.230003  4139.899902  59.063999
2026-10-09  81676.335938  91.290001  102.129997  4159.700195  60.669998
2026-10-10  82546.320312        NaN         NaN          NaN        NaN
2026-10-11  82912.226562        NaN         NaN          NaN        NaN

Price                                                        ...        Close  \
Ticker       ^FVX   ^IRX         ^IXIC          ^NDX   ^TNX  ...         GC=F
Date                                                         ...
2018-01-01    NaN    NaN           NaN           NaN    NaN  ...          NaN
2018-01-02  2.228  1.388   6937.649902   6431.589844  2.433  ...  1313.699951
2018-01-03  2.242  1.388   7017.069824   6520.029785  2.451  ...  1316.199951
2018-01-04  2.277  1.370   7089.500000   6595.750000  2.473  ...  1319.400024
2018-01-05  2.280  1.370   7105.740234   6613.129883  2.465  ...  1320.300049
...           ...    ...           ...           ...    ...  ...          ...
2026-10-07  5.072  4.037  27430.539062  30976.250000  5.341  ...  4140.700195
2026-10-08  5.070  4.043  27416.029297  30985.230469  5.324  ...  4157.000000
2026-10-09  4.996  4.045  27342.269531  30900.060547  5.236  ...  4216.299805
2026-10-10    NaN    NaN           NaN           NaN    NaN  ...          NaN
2026-10-11    NaN    NaN           NaN           NaN    NaN  ...          NaN

Price                                                                          \
Ticker           SI=F   ^FVX   ^IRX         ^IXIC          ^NDX   ^TNX   ^TYX
Date
2018-01-01        NaN    NaN    NaN           NaN           NaN    NaN    NaN
2018-01-02  17.121000  2.250  1.378   7006.899902   6511.339844  2.465  2.811
2018-01-03  17.184999  2.247  1.370   7065.529785   6575.799805  2.447  2.785
2018-01-04  17.188999  2.268  1.370   7077.910156   6584.580078  2.453  2.786
2018-01-05  17.205000  2.285  1.370   7136.560059   6653.290039  2.476  2.811
...               ...    ...    ...           ...           ...    ...    ...
2026-10-07  59.898998  5.021  4.037  27538.689453  31160.080078  5.277  5.661
2026-10-08  59.063999  4.991  4.043  27193.339844  30725.810547  5.231  5.606
2026-10-09  60.669998  5.021  4.057  27366.169922  30883.150391  5.244  5.600
2026-10-10        NaN    NaN    NaN           NaN           NaN    NaN    NaN
2026-10-11        NaN    NaN    NaN           NaN           NaN    NaN    NaN

Price
Ticker       ^VIX       ^VXN
Date
2018-01-01    NaN        NaN
2018-01-02   9.77  14.930000
2018-01-03   9.15  14.160000
2018-01-04   9.22  13.970000
2018-01-05   9.22  13.480000
...           ...        ...
2026-10-07  15.08  21.000000
2026-10-08  15.41  21.980000
2026-10-09  14.84  20.549999
2026-10-10    NaN        NaN
2026-10-11    NaN        NaN

[3206 rows x 26 columns]

In [111]:
# columns are (field, ticker): rename the ticker level with MACRO
df = df.rename(columns=MACRO, level=1)
df.head()

Price               Open                                                       \
Ticker           BTC-USD  crude_oil  US_dollar         gold     silver   ^FVX
Date
2018-01-01  14112.200195        NaN        NaN          NaN        NaN    NaN
2018-01-02  13625.000000  60.200001  92.239998  1302.300049  17.155001  2.228
2018-01-03  14978.200195  60.389999  91.820000  1320.000000  17.080000  2.242
2018-01-04  15270.700195  61.959999  92.220001  1319.400024  17.084999  2.277
2018-01-05  15477.200195  61.900002  91.870003  1320.300049  17.205000  2.280

Price                                                                          \
Ticker     3month_treasury_yield        ^IXIC   Nasdaq-100 10y_treasury_yield
Date
2018-01-01                   NaN          NaN          NaN                NaN
2018-01-02                 1.388  6937.649902  6431.589844              2.433
2018-01-03                 1.388  7017.069824  6520.029785              2.451
2018-01-04                 1.370  7089.500000  6595.750000              2.473
2018-01-05                 1.370  7105.740234  6613.129883              2.465

Price       ...        Close                                          \
Ticker      ...         gold     silver   ^FVX 3month_treasury_yield
Date        ...
2018-01-01  ...          NaN        NaN    NaN                   NaN
2018-01-02  ...  1313.699951  17.121000  2.250                 1.378
2018-01-03  ...  1316.199951  17.184999  2.247                 1.370
2018-01-04  ...  1319.400024  17.188999  2.268                 1.370
2018-01-05  ...  1320.300049  17.205000  2.285                 1.370

Price                                                                      \
Ticker            ^IXIC   Nasdaq-100 10y_treasury_yield   ^TYX Volatility
Date
2018-01-01          NaN          NaN                NaN    NaN        NaN
2018-01-02  7006.899902  6511.339844              2.465  2.811       9.77
2018-01-03  7065.529785  6575.799805              2.447  2.785       9.15
2018-01-04  7077.910156  6584.580078              2.453  2.786       9.22
2018-01-05  7136.560059  6653.290039              2.476  2.811       9.22

Price
Ticker       ^VXN
Date
2018-01-01    NaN
2018-01-02  14.93
2018-01-03  14.16
2018-01-04  13.97
2018-01-05  13.48

[5 rows x 26 columns]

In [112]:
open  = df["Open"]["Nasdaq-100"]
close = df["Close"]["Nasdaq-100"]

In [113]:
df["up/down"] = (close >= open).astype(int)

In [114]:
df.to_feather("data/treated.feather")