In [41]:
import pandas as pf
import numpy as np
import yfinance as yf

In [42]:
MACRO = {
    "^NDX": "Nasdaq-100",       # Nasdaq-100 index
    "^VIX": "Volatility",       # implied volatility (fear index)
    "^TNX": "10y_treasury_yield",       # 10-year Treasury yield
    "^IRX": "3month_treasury_yield",       # 3-month Treasury yield
    "CL=F": "crude_oil",       # WTI crude oil futures
    "DX-Y.NYB": "US_dollar",   # US dollar index
    "GC=F": "gold", 
    "SI=F": "silver"    # gold futures
}

tickers = list(MACRO.keys())
print(tickers)

['^NDX', '^VIX', '^TNX', '^IRX', 'CL=F', 'DX-Y.NYB', 'GC=F', 'SI=F']

In [49]:

# We download the market 
df = yf.download(tickers, start='2025-01-01', end='2026-10-12')[['Open', 'Close','High','Low']]

df

[*********************100%***********************]  8 of 8 completed

Price            Open                                             \
Ticker           CL=F    DX-Y.NYB         GC=F       SI=F   ^IRX
Date
2025-01-02  71.849998  108.529999  2641.000000  29.260000  4.208
2025-01-03  73.129997  109.199997  2671.100098  30.080000  4.197
2025-01-06  74.050003  108.919998  2652.800049  30.370001  4.188
2025-01-07  73.440002  108.339996  2647.100098  30.447001  4.195
2025-01-08  74.519997  108.620003  2662.899902  30.525000  4.205
...               ...         ...          ...        ...    ...
2026-10-05  91.769997  101.919998  4169.399902  61.520000  3.993
2026-10-06  89.269997  102.139999  4169.200195  60.919998  4.035
2026-10-07  89.959999  101.889999  4195.000000  60.880001  4.037
2026-10-08  89.000000  102.230003  4139.899902  59.063999  4.043
2026-10-09  91.290001  102.129997  4159.700195  60.669998  4.045

Price                                           Close              ...   High  \
Ticker              ^NDX   ^TNX       ^VIX       CL=F    DX-Y.NYB  ...   ^TNX
Date                                                               ...
2025-01-02  21120.050781  4.521  17.209999  73.129997  109.389999  ...  4.599
2025-01-03  21096.789062  4.545  17.660000  73.959999  108.949997  ...  4.600
2025-01-06  21551.179688  4.585  16.770000  73.559998  108.260002  ...  4.644
2025-01-07  21619.890625  4.634  16.480000  74.250000  108.540001  ...  4.699
2025-01-08  21156.759766  4.705  17.910000  73.320000  109.089996  ...  4.716
...                  ...    ...        ...        ...         ...  ...    ...
2026-10-05  30812.759766  5.273  16.240000  89.430000  102.169998  ...  5.349
2026-10-06  31255.400391  5.273  15.500000  89.440002  101.830002  ...  5.303
2026-10-07  30976.250000  5.341  15.210000  88.279999  102.239998  ...  5.364
2026-10-08  30985.230469  5.324  15.680000  91.489998  102.139999  ...  5.331
2026-10-09  30900.060547  5.236  15.340000  91.849998  102.209999  ...  5.280

Price                        Low                                             \
Ticker           ^VIX       CL=F    DX-Y.NYB         GC=F       SI=F   ^IRX
Date
2025-01-02  19.500000  71.790001  108.269997  2636.100098  29.260000  4.200
2025-01-03  17.940001  72.699997  108.900002  2649.699951  29.806000  4.190
2025-01-06  16.870001  73.199997  107.750000  2624.600098  29.959999  4.185
2025-01-07  18.900000  73.110001  107.849998  2643.500000  30.447001  4.195
2025-01-08  19.500000  73.160004  108.550003  2658.399902  30.280001  4.203
...               ...        ...         ...          ...        ...    ...
2026-10-05  16.379999  88.739998  101.860001  4150.399902  60.868999  3.990
2026-10-06  15.540000  86.860001  101.750000  4130.700195  60.919998  4.035
2026-10-07  16.010000  87.959999  101.889999  4091.199951  59.529999  4.035
2026-10-08  16.459999  88.769997  102.029999  4128.100098  58.915001  4.040
2026-10-09  15.340000  90.010002  101.919998  4156.100098  60.669998  4.045

Price
Ticker              ^NDX   ^TNX       ^VIX
Date
2025-01-02  20800.500000  4.517  16.959999
2025-01-03  21075.890625  4.539  16.110001
2025-01-06  21462.519531  4.579  15.710000
2025-01-07  21101.089844  4.626  15.790000
2025-01-08  20992.080078  4.673  17.370001
...                  ...    ...        ...
2026-10-05  30798.419922  5.264  15.480000
2026-10-06  31208.199219  5.256  14.960000
2026-10-07  30904.460938  5.269  14.970000
2026-10-08  30556.400391  5.223  15.150000
2026-10-09  30770.050781  5.234  14.770000

[449 rows x 32 columns]

In [50]:
# columns are (field, ticker): rename the ticker level with MACRO
df = df.rename(columns=MACRO, level=1)
df.head()

Price            Open                                      \
Ticker      crude_oil   US_dollar         gold     silver
Date
2025-01-02  71.849998  108.529999  2641.000000  29.260000
2025-01-03  73.129997  109.199997  2671.100098  30.080000
2025-01-06  74.050003  108.919998  2652.800049  30.370001
2025-01-07  73.440002  108.339996  2647.100098  30.447001
2025-01-08  74.519997  108.620003  2662.899902  30.525000

Price                                                                         \
Ticker     3month_treasury_yield    Nasdaq-100 10y_treasury_yield Volatility
Date
2025-01-02                 4.208  21120.050781              4.521  17.209999
2025-01-03                 4.197  21096.789062              4.545  17.660000
2025-01-06                 4.188  21551.179688              4.585  16.770000
2025-01-07                 4.195  21619.890625              4.634  16.480000
2025-01-08                 4.205  21156.759766              4.705  17.910000

Price           Close              ...               High             \
Ticker      crude_oil   US_dollar  ... 10y_treasury_yield Volatility
Date                               ...
2025-01-02  73.129997  109.389999  ...              4.599  19.500000
2025-01-03  73.959999  108.949997  ...              4.600  17.940001
2025-01-06  73.559998  108.260002  ...              4.644  16.870001
2025-01-07  74.250000  108.540001  ...              4.699  18.900000
2025-01-08  73.320000  109.089996  ...              4.716  19.500000

Price             Low                                      \
Ticker      crude_oil   US_dollar         gold     silver
Date
2025-01-02  71.790001  108.269997  2636.100098  29.260000
2025-01-03  72.699997  108.900002  2649.699951  29.806000
2025-01-06  73.199997  107.750000  2624.600098  29.959999
2025-01-07  73.110001  107.849998  2643.500000  30.447001
2025-01-08  73.160004  108.550003  2658.399902  30.280001

Price
Ticker     3month_treasury_yield    Nasdaq-100 10y_treasury_yield Volatility
Date
2025-01-02                 4.200  20800.500000              4.517  16.959999
2025-01-03                 4.190  21075.890625              4.539  16.110001
2025-01-06                 4.185  21462.519531              4.579  15.710000
2025-01-07                 4.195  21101.089844              4.626  15.790000
2025-01-08                 4.203  20992.080078              4.673  17.370001

[5 rows x 32 columns]

In [51]:
open  = df["Open"]["Nasdaq-100"]
close = df["Close"]["Nasdaq-100"]

In [52]:
df["up/down"] = (close >= open).astype(int)

In [53]:
df.to_feather("data/treated.feather")