In [41]:
import pandas as pf
import numpy as np
import yfinance as yf

In [98]:
MACRO = {
    "^NDX": "Nasdaq-100",       # Nasdaq-100 index
    "^VIX": "Volatility",       # implied volatility (fear index)
    "^TNX": "10y_treasury_yield",       # 10-year Treasury yield
    "^IRX": "3month_treasury_yield",       # 3-month Treasury yield
    "CL=F": "crude_oil",       # WTI crude oil futures
    "DX-Y.NYB": "US_dollar",   # US dollar index
    "GC=F": "gold", 
    "SI=F": "silver",  # gold futures
}

tickers = list(MACRO.keys())
print(tickers)

['^NDX', '^VIX', '^TNX', '^IRX', 'CL=F', 'DX-Y.NYB', 'GC=F', 'SI=F']

In [104]:
NASDAQ_FEATURES = {
    # --- INDICES ET VOLATILITÉ ---
    "^NDX": "Nasdaq_100",                     # Target index
    "^IXIC": "Nasdaq_composite",              # Broad tech market index
    "^VXN": "Nasdaq_volatility",              # Nasdaq-100 implied volatility (Tech fear index)
    "^VIX": "Volatility",                     # S&P 500 implied volatility (Market fear index)

    # --- interest ---
    "^IRX": "3month_treasury_yield",          # 3-month Treasury yield
    "^FVX": "5y_treasury_yield",              # 5-year Treasury yield
    "^TNX": "10y_treasury_yield",             # 10-year Treasury yield (Tech discounting rate)
    "^TYX": "30y_treasury_yield",             # 30-year Treasury yield

    # --- MATIÈRES PREMIÈRES ET DEVISES ---
    "DX-Y.NYB": "US_dollar",                  # US dollar index (DXY)
    "CL=F": "crude_oil",                      # WTI crude oil futures
    "GC=F": "gold",                           # Gold futures
    "SI=F": "silver",                         # Silver futures
    "BTC-USD": "Bitcoin",                     # Bitcoin USD (Risk-on sentiment proxy)
}

tickers1 = list(NASDAQ_FEATURES.keys())
print(tickers1)

['^NDX', '^IXIC', '^VXN', '^VIX', '^IRX', '^FVX', '^TNX', '^TYX', 'DX-Y.NYB', 'CL=F', 'GC=F', 'SI=F', 'BTC-USD']

In [115]:

# We download the market 
df = yf.download(tickers1, start='2018-01-01', end='2026-10-12')[['Open', 'Close','Volume']]

df

[*********************100%***********************]  13 of 13 completed

Price               Open                                                 \
Ticker           BTC-USD       CL=F    DX-Y.NYB         GC=F       SI=F
Date
2018-01-01  14112.200195        NaN         NaN          NaN        NaN
2018-01-02  13625.000000  60.200001   92.239998  1302.300049  17.155001
2018-01-03  14978.200195  60.389999   91.820000  1320.000000  17.080000
2018-01-04  15270.700195  61.959999   92.220001  1319.400024  17.084999
2018-01-05  15477.200195  61.900002   91.870003  1320.300049  17.205000
...                  ...        ...         ...          ...        ...
2026-10-07  85554.796875  89.959999  101.889999  4195.000000  60.880001
2026-10-08  83281.468750  89.000000  102.230003  4139.899902  59.063999
2026-10-09  81676.335938  91.290001  102.129997  4159.700195  60.669998
2026-10-10  82546.320312        NaN         NaN          NaN        NaN
2026-10-11  82912.226562        NaN         NaN          NaN        NaN

Price                                                        ...    Volume  \
Ticker       ^FVX   ^IRX         ^IXIC          ^NDX   ^TNX  ...      GC=F
Date                                                         ...
2018-01-01    NaN    NaN           NaN           NaN    NaN  ...       NaN
2018-01-02  2.228  1.388   6937.649902   6431.589844  2.433  ...      68.0
2018-01-03  2.242  1.388   7017.069824   6520.029785  2.451  ...      42.0
2018-01-04  2.277  1.370   7089.500000   6595.750000  2.473  ...       2.0
2018-01-05  2.280  1.370   7105.740234   6613.129883  2.465  ...       1.0
...           ...    ...           ...           ...    ...  ...       ...
2026-10-07  5.072  4.037  27430.539062  30976.250000  5.341  ...  163894.0
2026-10-08  5.070  4.043  27416.029297  30985.230469  5.324  ...  148432.0
2026-10-09  4.996  4.045  27342.269531  30900.060547  5.236  ...  148432.0
2026-10-10    NaN    NaN           NaN           NaN    NaN  ...       NaN
2026-10-11    NaN    NaN           NaN           NaN    NaN  ...       NaN

Price
Ticker       SI=F ^FVX ^IRX         ^IXIC          ^NDX ^TNX ^TYX ^VIX ^VXN
Date
2018-01-01    NaN  NaN  NaN           NaN           NaN  NaN  NaN  NaN  NaN
2018-01-02   34.0  0.0  0.0  1.929700e+09  1.929700e+09  0.0  0.0  0.0  0.0
2018-01-03    4.0  0.0  0.0  2.173130e+09  2.173130e+09  0.0  0.0  0.0  0.0
2018-01-04   34.0  0.0  0.0  2.103220e+09  2.103220e+09  0.0  0.0  0.0  0.0
2018-01-05    0.0  0.0  0.0  2.024000e+09  2.024000e+09  0.0  0.0  0.0  0.0
...           ...  ...  ...           ...           ...  ...  ...  ...  ...
2026-10-07  446.0  0.0  0.0  7.315500e+09  7.315500e+09  0.0  0.0  0.0  0.0
2026-10-08  244.0  0.0  0.0  8.820120e+09  8.820120e+09  0.0  0.0  0.0  0.0
2026-10-09  244.0  0.0  0.0  6.845310e+09  6.845310e+09  0.0  0.0  0.0  0.0
2026-10-10    NaN  NaN  NaN           NaN           NaN  NaN  NaN  NaN  NaN
2026-10-11    NaN  NaN  NaN           NaN           NaN  NaN  NaN  NaN  NaN

[3206 rows x 39 columns]

In [116]:
# columns are (field, ticker): rename the ticker level with MACRO
df = df.rename(columns=MACRO, level=1)
df.head()

Price               Open                                                       \
Ticker           BTC-USD  crude_oil  US_dollar         gold     silver   ^FVX
Date
2018-01-01  14112.200195        NaN        NaN          NaN        NaN    NaN
2018-01-02  13625.000000  60.200001  92.239998  1302.300049  17.155001  2.228
2018-01-03  14978.200195  60.389999  91.820000  1320.000000  17.080000  2.242
2018-01-04  15270.700195  61.959999  92.220001  1319.400024  17.084999  2.277
2018-01-05  15477.200195  61.900002  91.870003  1320.300049  17.205000  2.280

Price                                                                          \
Ticker     3month_treasury_yield        ^IXIC   Nasdaq-100 10y_treasury_yield
Date
2018-01-01                   NaN          NaN          NaN                NaN
2018-01-02                 1.388  6937.649902  6431.589844              2.433
2018-01-03                 1.388  7017.069824  6520.029785              2.451
2018-01-04                 1.370  7089.500000  6595.750000              2.473
2018-01-05                 1.370  7105.740234  6613.129883              2.465

Price       ... Volume                                                  \
Ticker      ...   gold silver ^FVX 3month_treasury_yield         ^IXIC
Date        ...
2018-01-01  ...    NaN    NaN  NaN                   NaN           NaN
2018-01-02  ...   68.0   34.0  0.0                   0.0  1.929700e+09
2018-01-03  ...   42.0    4.0  0.0                   0.0  2.173130e+09
2018-01-04  ...    2.0   34.0  0.0                   0.0  2.103220e+09
2018-01-05  ...    1.0    0.0  0.0                   0.0  2.024000e+09

Price
Ticker        Nasdaq-100 10y_treasury_yield ^TYX Volatility ^VXN
Date
2018-01-01           NaN                NaN  NaN        NaN  NaN
2018-01-02  1.929700e+09                0.0  0.0        0.0  0.0
2018-01-03  2.173130e+09                0.0  0.0        0.0  0.0
2018-01-04  2.103220e+09                0.0  0.0        0.0  0.0
2018-01-05  2.024000e+09                0.0  0.0        0.0  0.0

[5 rows x 39 columns]

In [117]:
open  = df["Open"]["Nasdaq-100"]
close = df["Close"]["Nasdaq-100"]

In [118]:
df["up/down"] = (close >= open).astype(int)

In [129]:
def date_split(df):
    d = df.index
    out = df.copy()
    out["day"] = d.day
    out["month"] = d.month
    out["day_month"] = d.dayofyear
    return out

In [130]:
df_dates = date_split(df)

In [131]:
df_dates

Price               Open                                                 \
Ticker           BTC-USD  crude_oil   US_dollar         gold     silver
Date
2018-01-01  14112.200195        NaN         NaN          NaN        NaN
2018-01-02  13625.000000  60.200001   92.239998  1302.300049  17.155001
2018-01-03  14978.200195  60.389999   91.820000  1320.000000  17.080000
2018-01-04  15270.700195  61.959999   92.220001  1319.400024  17.084999
2018-01-05  15477.200195  61.900002   91.870003  1320.300049  17.205000
...                  ...        ...         ...          ...        ...
2026-10-07  85554.796875  89.959999  101.889999  4195.000000  60.880001
2026-10-08  83281.468750  89.000000  102.230003  4139.899902  59.063999
2026-10-09  81676.335938  91.290001  102.129997  4159.700195  60.669998
2026-10-10  82546.320312        NaN         NaN          NaN        NaN
2026-10-11  82912.226562        NaN         NaN          NaN        NaN

Price                                                                \
Ticker       ^FVX 3month_treasury_yield         ^IXIC    Nasdaq-100
Date
2018-01-01    NaN                   NaN           NaN           NaN
2018-01-02  2.228                 1.388   6937.649902   6431.589844
2018-01-03  2.242                 1.388   7017.069824   6520.029785
2018-01-04  2.277                 1.370   7089.500000   6595.750000
2018-01-05  2.280                 1.370   7105.740234   6613.129883
...           ...                   ...           ...           ...
2026-10-07  5.072                 4.037  27430.539062  30976.250000
2026-10-08  5.070                 4.043  27416.029297  30985.230469
2026-10-09  4.996                 4.045  27342.269531  30900.060547
2026-10-10    NaN                   NaN           NaN           NaN
2026-10-11    NaN                   NaN           NaN           NaN

Price                          ...        Volume                \
Ticker     10y_treasury_yield  ...         ^IXIC    Nasdaq-100
Date                           ...
2018-01-01                NaN  ...           NaN           NaN
2018-01-02              2.433  ...  1.929700e+09  1.929700e+09
2018-01-03              2.451  ...  2.173130e+09  2.173130e+09
2018-01-04              2.473  ...  2.103220e+09  2.103220e+09
2018-01-05              2.465  ...  2.024000e+09  2.024000e+09
...                       ...  ...           ...           ...
2026-10-07              5.341  ...  7.315500e+09  7.315500e+09
2026-10-08              5.324  ...  8.820120e+09  8.820120e+09
2026-10-09              5.236  ...  6.845310e+09  6.845310e+09
2026-10-10                NaN  ...           NaN           NaN
2026-10-11                NaN  ...           NaN           NaN

Price                                              up/down day month day_month
Ticker     10y_treasury_yield ^TYX Volatility ^VXN
Date
2018-01-01                NaN  NaN        NaN  NaN       0   1     1         1
2018-01-02                0.0  0.0        0.0  0.0       1   2     1         2
2018-01-03                0.0  0.0        0.0  0.0       1   3     1         3
2018-01-04                0.0  0.0        0.0  0.0       0   4     1         4
2018-01-05                0.0  0.0        0.0  0.0       1   5     1         5
...                       ...  ...        ...  ...     ...  ..   ...       ...
2026-10-07                0.0  0.0        0.0  0.0       1   7    10       280
2026-10-08                0.0  0.0        0.0  0.0       0   8    10       281
2026-10-09                0.0  0.0        0.0  0.0       0   9    10       282
2026-10-10                NaN  NaN        NaN  NaN       0  10    10       283
2026-10-11                NaN  NaN        NaN  NaN       0  11    10       284

[3206 rows x 43 columns]

In [132]:
df_dates.to_feather("data/treated_dates.feather")